[book]
title = "moxwiki"
language = "en"

[output.html]
git-repository-url = "https://github.com/mox-desktop/moxwiki"
edit-url-template = "https://github.com/mox-desktop/moxwiki/edit/master/docs/{path}"
no-section-label = true

[output.html.fold]
enable = true

[preprocessor.alerts]
