services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  moxwiki:
    image: ghcr.io/unixpariah/moxwiki:prod
    platform: linux/arm64
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - web

networks:
  web:
    name: web
    driver: bridge

