apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/namespace.yaml
- k8s/service.yaml
- k8s/deployment.yaml
- k8s/ingress.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Kustomize
