apiVersion: v1
kind: Namespace
metadata:
  name: moxwiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moxwiki
  labels:
    app: moxwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moxwiki
  template:
    metadata:
      labels:
        app: moxwiki
    spec:
      containers:
        - name: moxwiki
          image: ghcr.io/unixpariah/moxwiki:prod
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: moxwiki
spec:
  type: ClusterIP
  ports:
    - port: 80  
      targetPort: 3000
  selector:
    app: moxwiki
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /moxwiki
            pathType: Prefix
            backend:
              service:
                name: moxwiki
                port:
                  number: 80

