name: Deploy image
on:
  push:
    branches:
      - main
permissions:
  packages: write
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: nix-community
          skipPush: true
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push with Nix
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ghcr.io/mox-desktop/moxwiki
        run: |
          nix build .
          
          docker load < result
          
          BUILT_IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep moxwiki | head -1)
          
          BRANCH=${GITHUB_REF#refs/heads/}
          COMMIT_SHA=${GITHUB_SHA::7}
          
          TAGS=(
            "${IMAGE_NAME}:latest"
            "${IMAGE_NAME}:${BRANCH}"
            "${IMAGE_NAME}:${COMMIT_SHA}"
            "${IMAGE_NAME}:${BRANCH}-${COMMIT_SHA}"
          )
          
          for tag in "${TAGS[@]}"; do
            echo "Tagging and pushing: $tag"
            docker tag "$BUILT_IMAGE" "$tag"
            docker push "$tag"
          done
